# 1) Grab the URL of YOUR Google Sheet and paste Here (make sure it ends with /edit -- clean off anything #gid= and beyond)
google_sheet: https://docs.google.com/spreadsheets/d/1ozeOJZ-ed1ZvIsc1Y26XP0m5ezqYc7Q_z1C4B4nlOE8/edit

# 2) Give your Jig a name
title: Up (Jig)

# 3) Change this to you Github user
github_user: deoogburn

# 3) Change this to your repo (when/if you change the name)
github_repo: zoo

# 4) This is the header logo, if you want to chnge
header_image: https://teh-jigz-up.github.io/teh-jigz-up/images/teh-jigz-up-header.png

# DO NOT CHANGE
markdown: kramdown

theme: jekyll-theme-minimal
